# =========================
# DATABASE (Railway MySQL)
# =========================
spring.datasource.url=jdbc:mysql://${mysql.railway.internal}:${railway}
spring.datasource.username=${root}
spring.datasource.password=${NYOUAwHozniVoNAgmOybWwUCmanuSUZR}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================
# SERVER PORT (Railway requirement)
# =========================
server.port=${PORT:8080}

# =========================
# STRIPE (optional)
# =========================
stripe.secret.key=${STRIPE_SECRET_KEY}